version: '3'
services:
  postgres:
    image: postgres:16
    ports:
      - "${PGPORT}:5432"
    volumes:
      - "./initdb.d-postgres:/docker-entrypoint-initdb.d:ro"
    command: "postgres -c 'app.jwt_secret=${PGRST_JWT_SECRET}'"
    environment:
      POSTGRES_DB: "${PGDATABASE}"
      POSTGRES_PASSWORD: "${PGPASSWORD}"
      POSTGRES_USER: "${PGUSER}"
  postgrest:
    image: postgrest/postgrest:v12.0.2
    depends_on:
      - postgres
    ports:
      - "${PGRST_SERVER_PORT}:3000"
    environment:
      PGRST_DB_ANON_ROLE: "anon"
      PGRST_DB_URI: "postgres://${PGUSER}:${PGPASSWORD}@postgres:5432/${PGDATABASE}"
      PGRST_JWT_SECRET: "${PGRST_JWT_SECRET}"
      PGRST_OPENAPI_SERVER_PROXY_URI: "http://127.0.0.1:3000"
